### ISSUE TITLE
Issue with Installation on Apple ARM64 Chips?

### ISSUE THREAD

**Issue by svats73** [msmbuilder/msmbuilder2022#14]
Trying to install MSMBuilder on a MacBook Pro with the M1 Pro Chip, running into the following error with conda installation pasted from terminal:

```
conda install conda-forge::testmsm     
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge::testmsm

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Is there any fix/way to install the package for the ARM architecture?

**Comment by bojunliu0818** [comment]
Thanks for raising the issue. "conda install" is a relatively old way for its installation, so it may have some issues. We are now switching "conda install" to "pip install" and we will make an announcement soon! For now, could you try the following commands to see if you can install msmbuilder locally?

>  conda create -n msm python=3.10

> conda activate msm

>  git clone https://github.com/msmbuilder/msmbuilder2022.git

>  pip install ./msmbuilder2022

**Comment by svats73** [comment]
Hi @bojunliu0818,

I tried the local installation of msmbuilder and received the error in the file I've attached below, it was over 620 lines so I decided to consolidate it to a text file. Let me know if there is something else I can do.

[error.txt](https://github.com/msmbuilder/msmbuilder2022/files/14078823/error.txt)

**Comment by bojunliu0818** [comment]
I am sorry for the late response! It seems like some core functions in msmbuilder are dependent on x86 instruction. We have also tried to build the wheel package of msmbuilder on Macos_arm64, but it didn't work. Thank you again for raising this issue, which is particularly important for the further maintenance of msmbuilder! Currently, macOS ARM64 support is not available for msmbuilder installation. We will address this issue in the upcoming release.
