### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by TianmingQu** [msmbuilder/msmbuilder2022#2]
I am currently trying to install the MSMbuilder 3.8 but some error jumps out as following:

Solving environment: | 

Found conflicts! Looking for incompatible packages.

This can take several minutes.  Press CTRL-C to abort.

failed                                                                                                                                                                                         

 

UnsatisfiableError: The following specifications were found

to be incompatible with the existing python installation in your environment:

 

Specifications:

 

  - msmbuilder -> python[version='2.7.*|3.5.*|3.4.*|3.6.*|3.3.*']

 

Your python: python=3.8

 

If python is on the left-most side of the chain, that's the version you've asked for.

When python appears to the right, that indicates that the thing on the left is somehow

not available for the python version you are constrained to. Note that conda will not

change your python version to a different minor version unless you explicitly specify

that.

 

 

Sorry to bother you but I have no idea how to fix this, maybe I need a lower version of python? Or do I need to install something?
Thanks a lot!

**Comment by bojunliu0818** [comment]
Hi Tianming, thanks for raising the issue! It seems like you are installing msmbuilder 3.8.0 using the command 'conda install -c omnia msmbuilder'? I agree that you need a lower version of python (python version <= 3.6), because msmbuilder 3.8.0 is not compatible with python > 3.6. Another option is that you could use the command 'conda install -c conda-forge testmsm' to install msmbuilder2022 (our recent github repository) instead. We will keep maintaining this package in the future. It is based on msmbuilder 3.8.0 and compatible with python = 3.7, 3.8, 3.9. Hope this could help! Thanks!

**Comment by TianmingQu** [comment]
> Hi Tianming, thanks for raising the issue! It seems like you are installing msmbuilder 3.8.0 using the command 'conda install -c omnia msmbuilder'? I agree that you need a lower version of python (python version <= 3.6), because msmbuilder 3.8.0 is not compatible with python > 3.6. Another option is that you could use the command 'conda install -c conda-forge testmsm' to install msmbuilder2022 (our recent github repository) instead. We will keep maintaining this package in the future. It is based on msmbuilder 3.8.0 and compatible with python = 3.7, 3.8, 3.9. Hope this could help! Thanks!

Hi Bojun,

Thanks for the suggestion, I also tried the new installation command today, but I still cannot installed it successfully.
My terminal reports a lot of conflicts when solving the environment, I took a short part of them as following:

Package pathtools conflicts for:
watchdog -> pathtools[version='>=0.1.1']
spyder -> watchdog[version='>=0.10.3'] -> pathtools[version='>=0.1.1']

Package archspec conflicts for:
conda-build -> conda[version='>=4.5'] -> archspec
conda-token -> conda[version='>=4.3'] -> archspec

Package jxrlib conflicts for:
anaconda==2021.05 -> imagecodecs==2021.3.31=py39h2ea9c00_0 -> jxrlib[version='>=1.1,<1.2.0a0']
anaconda==2021.05 -> jxrlib==1.1=haf1e3a3_2

Package qtawesome conflicts for:
anaconda==2021.05 -> qtawesome==1.0.2=pyhd3eb1b0_0
spyder -> qtawesome[version='>=0.4.1|>=0.5.7|>=1.0.2']
anaconda==2021.05 -> spyder==4.2.5=py37hecd8cb5_0 -> qtawesome[version='>=0.5.7']

Package spyder-kernels conflicts for:
anaconda==2021.05 -> spyder==4.2.5=py37hecd8cb5_0 -> spyder-kernels[version='>=1.10.2,<1.11.0']
anaconda==2021.05 -> spyder-kernels==1.10.2[build='py37hecd8cb5_0|py39hecd8cb5_0|py38hecd8cb5_0']
spyder -> spyder-kernels[version='0.*|>=0.1,<1|>=0.4.2,<1|>=0.4.3,<1|>=0.5.0,<1|>=1.10.0,<1.11.0|>=1.10.1,<1.11.0|>=1.10.2,<1.11.0|>=2.0.1,<2.1.0|>=2.0.2,<2.1.0|>=2.0.3,<2.1.0|>=2.0.4,<2.1.0|>=2.1.0,<2.2.0|>=2.1.1,<2.2.0|>=2.2.0,<2.3.0|>=2.2.1,<2.3.0|>=2.3.0,<2.4.0|>=2.3.1,<2.4.0|>=1.9.4,<1.10.0|>=1.9.2,<1.10.0|>=1.9.1,<1.10.0|>=1.9.0,<1.10.0|>=1.8.1,<1.9.0|>=1.8.1,<2.0.0|<1.0']

Package jupyterlab_server conflicts for:
anaconda==2021.05 -> jupyterlab_server==2.4.0=pyhd3eb1b0_0
_ipyw_jlab_nb_ext_conf -> jupyterlab -> jupyterlab_server[version='>=0.2.0,<0.3.0|>=1.0.0,<2.0.0|>=1.1.0,<2.0.0|>=2,<3|>=2.10,<3|>=2.3,<3|>=2.0.0,<3.0.0|>=1.1.5,<2.0.0']
anaconda==2021.05 -> jupyterlab==3.0.14=pyhd3eb1b0_1 -> jupyterlab_server[version='>=2.3,<3']
jupyterlab -> jupyterlab_server[version='>=0.2.0,<0.3.0|>=1.0.0,<2.0.0|>=1.1.0,<2.0.0|>=2,<3|>=2.10,<3|>=2.3,<3|>=2.0.0,<3.0.0|>=1.1.5,<2.0.0']

Package brunsli conflicts for:
anaconda==2021.05 -> brunsli==0.1=h23ab428_0
anaconda==2021.05 -> imagecodecs==2021.3.31=py39h2ea9c00_0 -> brunsli[version='>=0.1,<1.0a0']

Package immutables conflicts for:
sniffio -> contextvars[version='>=2.1'] -> immutables[version='0.5|0.6|>=0.9']
distributed -> contextvars -> immutables[version='0.5|0.6|>=0.9']

Package zope.event conflicts for:
anaconda==2021.05 -> gevent==21.1.2=py37h9ed2024_1 -> zope.event
anaconda==2021.05 -> zope.event==4.5.0[build='py38_0|py39hecd8cb5_0|py37_0']
gevent -> zope.eventThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0
  - applaunchservices -> __osx
  - spyder -> applaunchservices[version='>=0.3.0'] -> __osx

Your installed version is: 10.16


Have you ever meet something like this?

**Comment by bojunliu0818** [comment]
Interesting, I have never had this issue before. May you create a new conda environment to have a try again? Also, could you install msmbuilder first and then install other packages?

**Comment by TianmingQu** [comment]
Hi Bojun,
I think it worked, all the required packages were installed. But I still cannot import the msmbuilder module in jupyter-lab. Is there anything else I should do after the installation is finished? Or is there any way I can check if it is already installed successfully?

Best,
Tianming

发件人: Bojun Liu ***@***.***>
日期: 星期五, 2022年6月10日 上午11:55
收件人: msmbuilder/msmbuilder2022 ***@***.***>
抄送: Tianming Qu ***@***.***>, Author ***@***.***>
主题: Re: [msmbuilder/msmbuilder2022] About installation (Issue #2)

For example,

conda create -n msm python=3.8

conda acitivate msm

conda install -c conda-forge testmsm

―

**Comment by TianmingQu** [comment]
> For example,
> 
> ```
> conda create -n msm python=3.8
> conda acitivate msm
> conda install -c conda-forge testmsm
> ```

The terminal says all the required packages are installed! Thanks a lot!! But still, when I try the examples, the jupyter-lab says there is no module called msmbuilder. Could you give me some more instructions on this?

**Comment by bojunliu0818** [comment]
Sounds good! Are you opening jupyter lab in your new created environment? Maybe you could try this
'''
conda activate msm
conda install -c conda-forge jupyterlab
jupyter lab
'''

**Comment by bojunliu0818** [comment]
Sounds good! Are you opening jupyter lab in your new created environment? Maybe you could try this
```
conda activate msm
conda install -c conda-forge jupyterlab
jupyter lab
```

**Comment by TianmingQu** [comment]
Sorry to bother you on weekend, I tried the command you said, but it still says: No module named msmbuilder when I tried the examples in the “example” folder.

发件人: Bojun Liu ***@***.***>
日期: 星期五, 2022年6月10日 下午6:50
收件人: msmbuilder/msmbuilder2022 ***@***.***>
抄送: Tianming Qu ***@***.***>, Author ***@***.***>
主题: Re: [msmbuilder/msmbuilder2022] About installation (Issue #2)

Sounds good! Are you opening jupyter lab in your new created environment? Maybe you could try this

conda activate msm

conda install -c conda-forge jupyterlab

jupyter lab

―

**Comment by bojunliu0818** [comment]
Oh, this is strange. I think msmbuilder should be successfully installed in your 'msm' environment. Could you explain in detail how you try the examples? Or any screenshots about the error?

**Comment by TianmingQu** [comment]
Sure, do you think we can exchange our email address? I think this might be easier for our communication. I would be happy to if you are ok with that.

Tianming

发件人: Bojun Liu ***@***.***>
日期: 星期日, 2022年6月12日 下午4:24
收件人: msmbuilder/msmbuilder2022 ***@***.***>
抄送: Tianming Qu ***@***.***>, Author ***@***.***>
主题: Re: [msmbuilder/msmbuilder2022] About installation (Issue #2)

Oh, this is strange. I think msmbuilder should be successfully installed in your 'msm' environment. Could you explain in detail how you try the examples? Or any screenshots about the error?

―

**Comment by bojunliu0818** [comment]
Sure thing!

**Comment by bojunliu0818** [comment]
bliu293@wisc.edu
