### ISSUE TITLE
multichain.py mdtraj.utils.six module and mdtraj version specificity

### ISSUE THREAD

**Issue by qiushipeng** [msmbuilder/msmbuilder2022#21]
Hello,

I was trying to use the msmbuilder2022 package and run through the tutorial but I ran into an error when I ran 'msmb -h' as suggested to test the installation.

Error included below (apologies for the photo, clipboard copy is finicky) :

![image](https://github.com/msmbuilder/msmbuilder2022/assets/90414425/abc59ff0-3ff2-4460-89d2-0a8688c0551c)

Steps to Reproduce:

1. git clone and pip install the repo, no errors on install
2. `msmb -h`

Here is output of `pip list` :
![image](https://github.com/msmbuilder/msmbuilder2022/assets/90414425/91d6ab18-7868-4bd5-9d81-e80bf3fa2d7f)

I noticed that mdtraj in my pip list is set as 1.10.0. However,  I did not see a version requirement for mdtraj in the setup.py file, so I did some digging and found that mdtraj 1.10.0 seems not to include this six module and backtracked to 1.9.8 as is in their documentation as the most recent release.  However, 1.9.8 has cython issues with mdtraj as is noted in issues on their github so mdtraj 1.9.9 must be used. I tested this and found mdtraj 1.9.9 solved the problem.  Given that the package releases before and after 1.9.9 mdtraj are not compatible with msmbuilder2022, I suggest that setup.py requirements specify version 1.9.9 of mdtraj to prevent other users from running into this issue.

Thank you!

**Comment by bojunliu0818** [comment]
Hi qiushi, thank you for finding this issue! Your suggestion makes sense. If you are convenient, would you like to do a PR of it? Or I will fix it!

**Comment by bojunliu0818** [comment]
Thanks again for reporting it! It has been fixed by specifying mdtraj version 1.9.9. We will fix the dependency of mdtraj 1.10.0 later. I am going to close this issue.
