### ISSUE TITLE
No module named 'mdtraj.utils.six'

### ISSUE THREAD

**Issue by MilesYyh** [msmbuilder/msmbuilder2022#31]
Hi,Sir/Madam,
I imported the msmbuilder,however this have a bug. How can I fix this bug?
My mdtraj version is 1.10.0.
![Snipaste_2024-12-26_19-28-19](https://github.com/user-attachments/assets/b0f471b5-c489-4bb2-b0ec-5baf0b6daef6)
Thanks!
Best Wishes.

**Comment by bojunliu0818** [comment]
Hello, thanks for bringing this issue! As of mdtraj 1.10, the `mdtraj.utils.six` module has been removed. To resolve this, you can either:

1. Downgrade **mdtraj** to version **1.9.9**:
   ```bash
   pip install -U mdtraj==1.9.9
   ```
   
2. Install the most recent **msmbuilder2022** directly from the source code:
   ```bash
   git clone https://github.com/msmbuilder/msmbuilder2022.git
   python -m pip install ./msmbuilder2022
   ```

This issue has already been addressed in the current **msmbuilder2022** source code.

**Comment by MilesYyh** [comment]
Dear Sir/Madam,

Thanks a lot. 
Best Regards!

**Comment by bojunliu0818** [comment]
Sounds good, I will then close this issue.
